cd /tmp/DynaMoth_QuixBugs_LEVENSHTEIN_;
export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8 -Duser.language=en-US -Duser.country=US -Duser.language=en";
TZ="America/New_York"; export TZ;
export PATH="/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/:$PATH";
export JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/";
time java -Xmx4g -Xms1g -cp /home/tdurieux/defects4j4repair/script/../repair_tools/nopol.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin//../lib/tools.jar fr.inria.lille.repair.Main \
	--mode repair \
	--type pre_then_cond \
	--oracle angelic \
	--synthesis dynamoth \
	--flocal gzoltar \
	--json \
	--solver z3 \
	--solver-path /home/tdurieux/defects4j4repair/script/../libs/z3/build/z3 \
	--complianceLevel 8 \
	--source src/main/java \
	--classpath "target/classes:target/test-classes:/home/tdurieux/.m2/repository/junit/junit/4.11/junit-4.11.jar:/home/tdurieux/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/tdurieux/defects4j4repair/script/../repair_tools/nopol.jar";
	echo "\n\nNode: `hostname`\n";
	echo "\n\nDate: `date`\n";
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Duser.language=en-US -Duser.country=US -Duser.language=en
12:03:35.109 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Source files: [src/main/java]
12:03:35.111 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Classpath: [file:/tmp/DynaMoth_QuixBugs_LEVENSHTEIN_/target/classes/, file:/tmp/DynaMoth_QuixBugs_LEVENSHTEIN_/target/test-classes/, file:/home/tdurieux/.m2/repository/junit/junit/4.11/junit-4.11.jar, file:/home/tdurieux/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar, file:/home/tdurieux/defects4j4repair/script/../repair_tools/nopol.jar]
12:03:35.112 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Statement type: PRE_THEN_COND
12:03:35.112 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Args: [java_testcases.junit.LEVENSHTEIN_Test]
12:03:35.113 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Config: Config{synthesisDepth=3, collectStaticMethods=true, collectStaticFields=false, collectLiterals=false, onlyOneSynthesisResult=true, sortExpressions=true, maxLineInvocationPerTest=250, timeoutMethodInvocation=2000, dataCollectionTimeoutInSecondForSynthesis=900, addWeight=0.19478, subWeight=0.04554, mulWeight=0.0102, divWeight=0.00613, andWeight=0.10597, orWeight=0.05708, eqWeight=0.22798, nEqWeight=0.0, lessEqWeight=0.0255, lessWeight=0.0947, methodCallWeight=0.1, fieldAccessWeight=0.08099, constantWeight=0.14232, variableWeight=0.05195, mode=REPAIR, type=PRE_THEN_COND, synthesis=DYNAMOTH, oracle=ANGELIC, solver=Z3, solverPath='/home/tdurieux/defects4j4repair/script/../libs/z3/build/z3', projectSources=[src/main/java], projectClasspath='[Ljava.net.URL;@2ff4f00f', projectTests=[java_testcases.junit.LEVENSHTEIN_Test], complianceLevel=8, outputFolder=., json=true}
12:03:35.113 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Available processors (cores): 32
12:03:35.117 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Free memory: 940 MB
12:03:35.118 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Maximum memory: 3 GB
12:03:35.118 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Total memory available to JVM: 981 MB
12:03:35.118 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Java version: 1.8.0_181
12:03:35.119 [main] INFO  fr.inria.lille.repair.nopol.NoPol - JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/
12:03:35.119 [main] INFO  fr.inria.lille.repair.nopol.NoPol - PATH: /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/:/usr/lib/oar/oardodo:/usr/lib/oar/oardodo:/usr/local/bin:/usr/bin:/bin:/usr/games
12:03:37.860 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #1
12:03:37.861 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LEVENSHTEIN:22 which is executed by 5 tests
-1975184878
12:03:38.020 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #2
12:03:38.021 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LEVENSHTEIN:21 which is executed by 5 tests
-1975184878
12:03:38.055 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #3
12:03:38.056 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LEVENSHTEIN:20 which is executed by 5 tests
-1975184878
12:03:38.089 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #4
12:03:38.090 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LEVENSHTEIN:19 which is executed by 5 tests
-1975184878
12:03:38.133 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalAdder
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
12:03:39.363 [pool-4-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (1197 ms)
<> Total tests run: 30
<> Ignored tests: 5
<> Failed tests: 25
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)

12:03:39.679 [pool-3-thread-1] ERROR x.java.compiler.DynamicClassCompiler - [Compilation errors]
LEVENSHTEIN.java:21: error: missing return statement
    }
    ^
xxl.java.compiler.DynamicCompilationException: Aborting: dynamic compilation failed
	at xxl.java.compiler.DynamicClassCompiler.runCompilationTask(DynamicClassCompiler.java:99)
	at xxl.java.compiler.DynamicClassCompiler.javaBytecodeFor(DynamicClassCompiler.java:67)
	at fr.inria.lille.commons.spoon.SpoonedFile.compilationFor(SpoonedFile.java:203)
	at fr.inria.lille.commons.spoon.SpoonedFile.compileModelledClasses(SpoonedFile.java:177)
	at fr.inria.lille.commons.spoon.SpoonedFile.dumpedToClassLoader(SpoonedFile.java:130)
	at fr.inria.lille.commons.spoon.SpoonedFile.processedAndDumpedToClassLoader(SpoonedFile.java:140)
	at fr.inria.lille.commons.spoon.SpoonedFile.processedAndDumpedToClassLoader(SpoonedFile.java:135)
	at fr.inria.lille.repair.nopol.synth.dynamoth.DynamothSynthesizer.findAngelicValuesAndBuildPatch(DynamothSynthesizer.java:69)
	at fr.inria.lille.repair.nopol.NoPol.runNopolProcessor(NoPol.java:295)
	at fr.inria.lille.repair.nopol.NoPol.access$000(NoPol.java:81)
	at fr.inria.lille.repair.nopol.NoPol$1.call(NoPol.java:260)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
12:03:39.680 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #5
12:03:39.680 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LEVENSHTEIN:17 which is executed by 5 tests
-1975184878
12:03:39.713 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalAdder
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
12:03:40.935 [pool-6-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (1218 ms)
<> Total tests run: 30
<> Ignored tests: 5
<> Failed tests: 25
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)

12:03:40.998 [pool-5-thread-1] ERROR x.java.compiler.DynamicClassCompiler - [Compilation errors]
LEVENSHTEIN.java:21: error: missing return statement
    }
    ^
xxl.java.compiler.DynamicCompilationException: Aborting: dynamic compilation failed
	at xxl.java.compiler.DynamicClassCompiler.runCompilationTask(DynamicClassCompiler.java:99)
	at xxl.java.compiler.DynamicClassCompiler.javaBytecodeFor(DynamicClassCompiler.java:67)
	at fr.inria.lille.commons.spoon.SpoonedFile.compilationFor(SpoonedFile.java:203)
	at fr.inria.lille.commons.spoon.SpoonedFile.compileModelledClasses(SpoonedFile.java:177)
	at fr.inria.lille.commons.spoon.SpoonedFile.dumpedToClassLoader(SpoonedFile.java:130)
	at fr.inria.lille.commons.spoon.SpoonedFile.processedAndDumpedToClassLoader(SpoonedFile.java:140)
	at fr.inria.lille.commons.spoon.SpoonedFile.processedAndDumpedToClassLoader(SpoonedFile.java:135)
	at fr.inria.lille.repair.nopol.synth.dynamoth.DynamothSynthesizer.findAngelicValuesAndBuildPatch(DynamothSynthesizer.java:69)
	at fr.inria.lille.repair.nopol.NoPol.runNopolProcessor(NoPol.java:295)
	at fr.inria.lille.repair.nopol.NoPol.access$000(NoPol.java:81)
	at fr.inria.lille.repair.nopol.NoPol$1.call(NoPol.java:260)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
12:03:40.999 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #6
12:03:40.999 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LEVENSHTEIN:16 which is executed by 5 tests
-1975184878
12:03:41.032 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalAdder
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
12:03:41.998 [pool-8-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (962 ms)
<> Total tests run: 30
<> Ignored tests: 5
<> Failed tests: 25
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)

12:03:42.057 [pool-7-thread-1] ERROR x.java.compiler.DynamicClassCompiler - [Compilation errors]
LEVENSHTEIN.java:19: error: missing return statement
    }
    ^
xxl.java.compiler.DynamicCompilationException: Aborting: dynamic compilation failed
	at xxl.java.compiler.DynamicClassCompiler.runCompilationTask(DynamicClassCompiler.java:99)
	at xxl.java.compiler.DynamicClassCompiler.javaBytecodeFor(DynamicClassCompiler.java:67)
	at fr.inria.lille.commons.spoon.SpoonedFile.compilationFor(SpoonedFile.java:203)
	at fr.inria.lille.commons.spoon.SpoonedFile.compileModelledClasses(SpoonedFile.java:177)
	at fr.inria.lille.commons.spoon.SpoonedFile.dumpedToClassLoader(SpoonedFile.java:130)
	at fr.inria.lille.commons.spoon.SpoonedFile.processedAndDumpedToClassLoader(SpoonedFile.java:140)
	at fr.inria.lille.commons.spoon.SpoonedFile.processedAndDumpedToClassLoader(SpoonedFile.java:135)
	at fr.inria.lille.repair.nopol.synth.dynamoth.DynamothSynthesizer.findAngelicValuesAndBuildPatch(DynamothSynthesizer.java:69)
	at fr.inria.lille.repair.nopol.NoPol.runNopolProcessor(NoPol.java:295)
	at fr.inria.lille.repair.nopol.NoPol.access$000(NoPol.java:81)
	at fr.inria.lille.repair.nopol.NoPol$1.call(NoPol.java:260)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
12:03:42.057 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalReplacer
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
12:03:42.983 [pool-10-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (923 ms)
<> Total tests run: 30
<> Ignored tests: 5
<> Failed tests: 25
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)

12:03:46.415 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #7
12:03:46.419 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LEVENSHTEIN:15 which is executed by 6 tests
-1975184878
12:03:46.453 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalAdder
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
12:03:47.430 [pool-22-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (974 ms)
<> Total tests run: 30
<> Ignored tests: 5
<> Failed tests: 25
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)

12:03:47.488 [pool-21-thread-1] ERROR x.java.compiler.DynamicClassCompiler - [Compilation errors]
LEVENSHTEIN.java:21: error: missing return statement
    }
    ^
xxl.java.compiler.DynamicCompilationException: Aborting: dynamic compilation failed
	at xxl.java.compiler.DynamicClassCompiler.runCompilationTask(DynamicClassCompiler.java:99)
	at xxl.java.compiler.DynamicClassCompiler.javaBytecodeFor(DynamicClassCompiler.java:67)
	at fr.inria.lille.commons.spoon.SpoonedFile.compilationFor(SpoonedFile.java:203)
	at fr.inria.lille.commons.spoon.SpoonedFile.compileModelledClasses(SpoonedFile.java:177)
	at fr.inria.lille.commons.spoon.SpoonedFile.dumpedToClassLoader(SpoonedFile.java:130)
	at fr.inria.lille.commons.spoon.SpoonedFile.processedAndDumpedToClassLoader(SpoonedFile.java:140)
	at fr.inria.lille.commons.spoon.SpoonedFile.processedAndDumpedToClassLoader(SpoonedFile.java:135)
	at fr.inria.lille.repair.nopol.synth.dynamoth.DynamothSynthesizer.findAngelicValuesAndBuildPatch(DynamothSynthesizer.java:69)
	at fr.inria.lille.repair.nopol.NoPol.runNopolProcessor(NoPol.java:295)
	at fr.inria.lille.repair.nopol.NoPol.access$000(NoPol.java:81)
	at fr.inria.lille.repair.nopol.NoPol$1.call(NoPol.java:260)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
12:03:47.489 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #8
12:03:47.489 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LEVENSHTEIN:14 which is executed by 6 tests
-1975184878
12:03:47.523 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalReplacer
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
12:03:48.526 [pool-24-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (999 ms)
<> Total tests run: 30
<> Ignored tests: 5
<> Failed tests: 25
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)

12:03:48.591 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - ----INFORMATION----
12:03:48.601 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb classes : 3
12:03:48.601 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb methods : 9
12:03:48.601 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb Statements Analyzed : 6
12:03:48.601 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb Statements with Angelic Value Found : 0
12:03:48.601 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - NoPol Execution time : 13484ms
12:03:48.601 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - 
NO_ANGELIC_VALUE
Command exited with non-zero status 255
50.16user 1.64system 0:14.40elapsed 359%CPU (0avgtext+0avgdata 1980116maxresident)k
45752inputs+5568outputs (3major+649833minor)pagefaults 0swaps


Node: grisou-28.nancy.grid5000.fr



Date: Sun Dec  2 12:03:48 EST 2018

