cd /tmp/Nopol_QuixBugs_LEVENSHTEIN_;
export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8 -Duser.language=en-US -Duser.country=US -Duser.language=en";
TZ="America/New_York"; export TZ;
export PATH="/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/:$PATH";
export JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/";
time java -Xmx4g -Xms1g -cp /home/tdurieux/defects4j4repair/script/../repair_tools/nopol.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin//../lib/tools.jar fr.inria.lille.repair.Main \
	--mode repair \
	--type pre_then_cond \
	--oracle angelic \
	--synthesis smt \
	--flocal gzoltar \
	--json \
	--solver z3 \
	--solver-path /home/tdurieux/defects4j4repair/script/../libs/z3/build/z3 \
	--complianceLevel 8 \
	--source src/main/java \
	--classpath "target/classes:target/test-classes:/home/tdurieux/.m2/repository/junit/junit/4.11/junit-4.11.jar:/home/tdurieux/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/tdurieux/defects4j4repair/script/../repair_tools/nopol.jar";
	echo "\n\nNode: `hostname`\n";
	echo "\n\nDate: `date`\n";
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Duser.language=en-US -Duser.country=US -Duser.language=en
14:41:10.633 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Source files: [src/main/java]
14:41:10.652 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Classpath: [file:/tmp/Nopol_QuixBugs_LEVENSHTEIN_/target/classes/, file:/tmp/Nopol_QuixBugs_LEVENSHTEIN_/target/test-classes/, file:/home/tdurieux/.m2/repository/junit/junit/4.11/junit-4.11.jar, file:/home/tdurieux/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar, file:/home/tdurieux/defects4j4repair/script/../repair_tools/nopol.jar]
14:41:10.652 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Statement type: PRE_THEN_COND
14:41:10.652 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Args: [java_testcases.junit.LEVENSHTEIN_Test]
14:41:10.654 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Config: Config{synthesisDepth=3, collectStaticMethods=true, collectStaticFields=false, collectLiterals=false, onlyOneSynthesisResult=true, sortExpressions=true, maxLineInvocationPerTest=250, timeoutMethodInvocation=2000, dataCollectionTimeoutInSecondForSynthesis=900, addWeight=0.19478, subWeight=0.04554, mulWeight=0.0102, divWeight=0.00613, andWeight=0.10597, orWeight=0.05708, eqWeight=0.22798, nEqWeight=0.0, lessEqWeight=0.0255, lessWeight=0.0947, methodCallWeight=0.1, fieldAccessWeight=0.08099, constantWeight=0.14232, variableWeight=0.05195, mode=REPAIR, type=PRE_THEN_COND, synthesis=SMT, oracle=ANGELIC, solver=Z3, solverPath='/home/tdurieux/defects4j4repair/script/../libs/z3/build/z3', projectSources=[src/main/java], projectClasspath='[Ljava.net.URL;@66d33a', projectTests=[java_testcases.junit.LEVENSHTEIN_Test], complianceLevel=8, outputFolder=., json=true}
14:41:10.654 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Available processors (cores): 4
14:41:10.659 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Free memory: 961 MB
14:41:10.659 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Maximum memory: 3 GB
14:41:10.660 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Total memory available to JVM: 981 MB
14:41:10.660 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Java version: 1.8.0_181
14:41:10.661 [main] INFO  fr.inria.lille.repair.nopol.NoPol - JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/
14:41:10.661 [main] INFO  fr.inria.lille.repair.nopol.NoPol - PATH: /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/:/usr/lib/oar/oardodo:/usr/lib/oar/oardodo:/usr/local/bin:/usr/bin:/bin:/usr/games
14:41:14.351 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #1
14:41:14.352 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LEVENSHTEIN:22 which is executed by 5 tests
-1975184878
14:41:14.574 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #2
14:41:14.574 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LEVENSHTEIN:21 which is executed by 5 tests
-1975184878
14:41:14.617 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #3
14:41:14.618 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LEVENSHTEIN:20 which is executed by 5 tests
-1975184878
14:41:14.659 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #4
14:41:14.659 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LEVENSHTEIN:19 which is executed by 5 tests
-1975184878
14:41:14.711 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalAdder
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
14:41:16.247 [pool-4-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (1508 ms)
<> Total tests run: 30
<> Ignored tests: 5
<> Failed tests: 25
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)

14:41:16.875 [pool-3-thread-1] ERROR x.java.compiler.DynamicClassCompiler - [Compilation errors]
LEVENSHTEIN.java:28: error: missing return statement
    }
    ^
14:41:16.878 [pool-3-thread-1] ERROR f.i.l.r.n.s.ConstraintModelBuilder - Unable to compile the change: 
public class LEVENSHTEIN {
    public static int levenshtein(java.lang.String source, java.lang.String target) {
        if ((source.isEmpty()) || (target.isEmpty())) {
            return source.isEmpty() ? target.length() : source.length();
        }else
            if ((source.charAt(0)) == (target.charAt(0))) {
                return 1 + (java_programs.LEVENSHTEIN.levenshtein(source.substring(1), target.substring(1)));
            }else {
                boolean spoonDefaultValue = false;
                try {
                    spoonDefaultValue = true;
                } catch (java.lang.Exception __NopolProcessorException) {
                }
                boolean runtimeAngelicValue = fr.inria.lille.repair.nopol.synth.AngelicExecution.angelicValue(spoonDefaultValue);
                if (fr.inria.lille.commons.trace.RuntimeValues.instance(0).isEnabled()) {
                    fr.inria.lille.commons.trace.RuntimeValues.instance(0).collectionStarts();
                    try{fr.inria.lille.commons.trace.RuntimeValues.instance(0).collectInput("source",source);} catch (Exception ex1) {ex1.printStackTrace();};
                    try{fr.inria.lille.commons.trace.RuntimeValues.instance(0).collectInput("target",target);} catch (Exception ex1) {ex1.printStackTrace();};
                    fr.inria.lille.commons.trace.RuntimeValues.instance(0).collectOutput(runtimeAngelicValue);
                    fr.inria.lille.commons.trace.RuntimeValues.instance(0).collectionEnds();
                }
                if (runtimeAngelicValue)
                    return 1 + (java.lang.Math.min(java.lang.Math.min(java_programs.LEVENSHTEIN.levenshtein(source, target.substring(1)), java_programs.LEVENSHTEIN.levenshtein(source.substring(1), target.substring(1))), java_programs.LEVENSHTEIN.levenshtein(source.substring(1), target)));

            }

    }
}
14:41:16.878 [pool-2-thread-1] ERROR fr.inria.lille.repair.nopol.NoPol - Error ExecutionException java.util.concurrent.ExecutionException: xxl.java.compiler.DynamicCompilationException: Aborting: dynamic compilation failed
14:41:16.879 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #5
14:41:16.879 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LEVENSHTEIN:17 which is executed by 5 tests
-1975184878
14:41:16.929 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalAdder
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
14:41:18.458 [pool-6-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (1501 ms)
<> Total tests run: 30
<> Ignored tests: 5
<> Failed tests: 25
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)

14:41:18.616 [pool-5-thread-1] ERROR x.java.compiler.DynamicClassCompiler - [Compilation errors]
LEVENSHTEIN.java:28: error: missing return statement
    }
    ^
14:41:18.618 [pool-5-thread-1] ERROR f.i.l.r.n.s.ConstraintModelBuilder - Unable to compile the change: 
public class LEVENSHTEIN {
    public static int levenshtein(java.lang.String source, java.lang.String target) {
        if ((source.isEmpty()) || (target.isEmpty())) {
            return source.isEmpty() ? target.length() : source.length();
        }else
            if ((source.charAt(0)) == (target.charAt(0))) {
                boolean spoonDefaultValue = false;
                try {
                    spoonDefaultValue = true;
                } catch (java.lang.Exception __NopolProcessorException) {
                }
                boolean runtimeAngelicValue = fr.inria.lille.repair.nopol.synth.AngelicExecution.angelicValue(spoonDefaultValue);
                if (fr.inria.lille.commons.trace.RuntimeValues.instance(1).isEnabled()) {
                    fr.inria.lille.commons.trace.RuntimeValues.instance(1).collectionStarts();
                    try{fr.inria.lille.commons.trace.RuntimeValues.instance(1).collectInput("source",source);} catch (Exception ex1) {ex1.printStackTrace();};
                    try{fr.inria.lille.commons.trace.RuntimeValues.instance(1).collectInput("target",target);} catch (Exception ex1) {ex1.printStackTrace();};
                    fr.inria.lille.commons.trace.RuntimeValues.instance(1).collectOutput(runtimeAngelicValue);
                    fr.inria.lille.commons.trace.RuntimeValues.instance(1).collectionEnds();
                }
                if (runtimeAngelicValue)
                    return 1 + (java_programs.LEVENSHTEIN.levenshtein(source.substring(1), target.substring(1)));

            }else {
                return 1 + (java.lang.Math.min(java.lang.Math.min(java_programs.LEVENSHTEIN.levenshtein(source, target.substring(1)), java_programs.LEVENSHTEIN.levenshtein(source.substring(1), target.substring(1))), java_programs.LEVENSHTEIN.levenshtein(source.substring(1), target)));
            }

    }
}
14:41:18.619 [pool-2-thread-1] ERROR fr.inria.lille.repair.nopol.NoPol - Error ExecutionException java.util.concurrent.ExecutionException: xxl.java.compiler.DynamicCompilationException: Aborting: dynamic compilation failed
14:41:18.619 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #6
14:41:18.619 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LEVENSHTEIN:16 which is executed by 5 tests
-1975184878
14:41:18.676 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalAdder
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
14:41:20.220 [pool-8-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (1536 ms)
<> Total tests run: 30
<> Ignored tests: 5
<> Failed tests: 25
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)

14:41:20.322 [pool-7-thread-1] ERROR x.java.compiler.DynamicClassCompiler - [Compilation errors]
LEVENSHTEIN.java:27: error: missing return statement
    }
    ^
14:41:20.324 [pool-7-thread-1] ERROR f.i.l.r.n.s.ConstraintModelBuilder - Unable to compile the change: 
public class LEVENSHTEIN {
    public static int levenshtein(java.lang.String source, java.lang.String target) {
        if ((source.isEmpty()) || (target.isEmpty())) {
            return source.isEmpty() ? target.length() : source.length();
        }else {
            boolean spoonDefaultValue = false;
            try {
                spoonDefaultValue = true;
            } catch (java.lang.Exception __NopolProcessorException) {
            }
            boolean runtimeAngelicValue = fr.inria.lille.repair.nopol.synth.AngelicExecution.angelicValue(spoonDefaultValue);
            if (fr.inria.lille.commons.trace.RuntimeValues.instance(2).isEnabled()) {
                fr.inria.lille.commons.trace.RuntimeValues.instance(2).collectionStarts();
                try{fr.inria.lille.commons.trace.RuntimeValues.instance(2).collectInput("0",0);} catch (Exception ex1) {ex1.printStackTrace();};
                try{fr.inria.lille.commons.trace.RuntimeValues.instance(2).collectInput("source",source);} catch (Exception ex1) {ex1.printStackTrace();};
                try{fr.inria.lille.commons.trace.RuntimeValues.instance(2).collectInput("target",target);} catch (Exception ex1) {ex1.printStackTrace();};
                fr.inria.lille.commons.trace.RuntimeValues.instance(2).collectOutput(runtimeAngelicValue);
                fr.inria.lille.commons.trace.RuntimeValues.instance(2).collectionEnds();
            }
            if (runtimeAngelicValue) if ((source.charAt(0)) == (target.charAt(0))) {
                return 1 + (java_programs.LEVENSHTEIN.levenshtein(source.substring(1), target.substring(1)));
            }else {
                return 1 + (java.lang.Math.min(java.lang.Math.min(java_programs.LEVENSHTEIN.levenshtein(source, target.substring(1)), java_programs.LEVENSHTEIN.levenshtein(source.substring(1), target.substring(1))), java_programs.LEVENSHTEIN.levenshtein(source.substring(1), target)));
            }
        }
    }
}
14:41:20.325 [pool-2-thread-1] ERROR fr.inria.lille.repair.nopol.NoPol - Error ExecutionException java.util.concurrent.ExecutionException: xxl.java.compiler.DynamicCompilationException: Aborting: dynamic compilation failed
14:41:20.325 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalReplacer
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
14:41:21.651 [pool-10-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (1311 ms)
<> Total tests run: 30
<> Ignored tests: 5
<> Failed tests: 25
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)

java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
14:41:21.981 [pool-11-thread-1] INFO  f.i.l.c.t.SpecificationTestCasesListener - Tests run finished (209 ms)
<> Total tests run: 1
<> Ignored tests: 0
<> Failed tests: 1
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)

java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
14:41:22.014 [pool-12-thread-1] INFO  f.i.l.c.t.SpecificationTestCasesListener - Tests run finished (32 ms)
<> Total tests run: 1
<> Ignored tests: 0
<> Failed tests: 1
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)

java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
14:41:22.019 [pool-13-thread-1] INFO  f.i.l.c.t.SpecificationTestCasesListener - Tests run finished (4 ms)
<> Total tests run: 1
<> Ignored tests: 0
<> Failed tests: 1
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)

java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
14:41:22.085 [pool-14-thread-1] INFO  f.i.l.c.t.SpecificationTestCasesListener - Tests run finished (65 ms)
<> Total tests run: 1
<> Ignored tests: 0
<> Failed tests: 1
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)

java.lang.Exception: test timed out after 3000 milliseconds
    at java.lang.String.intern(Native Method)
    at fr.inria.lille.commons.trace.collector.ValueCollector.collectWith(ValueCollector.java:31)
    at fr.inria.lille.commons.trace.collector.ValueCollector.collectFrom(ValueCollector.java:17)
    at fr.inria.lille.commons.trace.RuntimeValues.collectInput(RuntimeValues.java:81)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:15)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:24)
14:41:25.089 [pool-15-thread-1] INFO  f.i.l.c.t.SpecificationTestCasesListener - Tests run finished (3003 ms)
<> Total tests run: 1
<> Ignored tests: 0
<> Failed tests: 1
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[test timed out after 3000 milliseconds]
java.lang.Exception: test timed out after 3000 milliseconds    at java.lang.String.intern(Native Method)
    at fr.inria.lille.commons.trace.collector.ValueCollector.collectWith(ValueCollector.java:31)
    at fr.inria.lille.commons.trace.collector.ValueCollector.collectFrom(ValueCollector.java:17)
    at fr.inria.lille.commons.trace.RuntimeValues.collectInput(RuntimeValues.java:81)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:15)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:24)

java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
14:41:25.178 [pool-16-thread-1] INFO  f.i.l.c.t.SpecificationTestCasesListener - Tests run finished (88 ms)
<> Total tests run: 1
<> Ignored tests: 0
<> Failed tests: 1
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)

java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
14:41:25.179 [pool-17-thread-1] INFO  f.i.l.c.t.SpecificationTestCasesListener - Tests run finished (0 ms)
<> Total tests run: 1
<> Ignored tests: 0
<> Failed tests: 1
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)

java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
14:41:25.181 [pool-18-thread-1] INFO  f.i.l.c.t.SpecificationTestCasesListener - Tests run finished (1 ms)
<> Total tests run: 1
<> Ignored tests: 0
<> Failed tests: 1
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)

java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
14:41:25.182 [pool-19-thread-1] INFO  f.i.l.c.t.SpecificationTestCasesListener - Tests run finished (1 ms)
<> Total tests run: 1
<> Ignored tests: 0
<> Failed tests: 1
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)

java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
14:41:25.184 [pool-20-thread-1] INFO  f.i.l.c.t.SpecificationTestCasesListener - Tests run finished (1 ms)
<> Total tests run: 1
<> Ignored tests: 0
<> Failed tests: 1
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)

14:41:25.185 [pool-9-thread-1] DEBUG tests.output - Failing tests with false: 
[test_0(java_testcases.junit.LEVENSHTEIN_Test): expected:<3> but was:<8>, test_1(java_testcases.junit.LEVENSHTEIN_Test): expected:<3> but was:<7>, test_6(java_testcases.junit.LEVENSHTEIN_Test): expected:<4> but was:<5>, test_4(java_testcases.junit.LEVENSHTEIN_Test): expected:<2> but was:<7>, test_2(java_testcases.junit.LEVENSHTEIN_Test): test timed out after 3000 milliseconds]
14:41:25.185 [pool-9-thread-1] DEBUG tests.output - Failing tests with true: 
[test_0(java_testcases.junit.LEVENSHTEIN_Test): expected:<3> but was:<8>, test_1(java_testcases.junit.LEVENSHTEIN_Test): expected:<3> but was:<7>, test_6(java_testcases.junit.LEVENSHTEIN_Test): expected:<4> but was:<5>, test_4(java_testcases.junit.LEVENSHTEIN_Test): expected:<2> but was:<7>, test_2(java_testcases.junit.LEVENSHTEIN_Test): expected:<8> but was:<13>]
14:41:25.185 [pool-9-thread-1] INFO  f.i.l.r.n.synth.SMTNopolSynthesizer - Not enough specifications: 0. A trivial patch is "true" or "false", please write new tests specifying SourceLocation java_programs.LEVENSHTEIN:16.
14:41:25.185 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #7
14:41:25.185 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LEVENSHTEIN:15 which is executed by 6 tests
-1975184878
14:41:25.226 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalAdder
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
14:41:26.638 [pool-22-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (1409 ms)
<> Total tests run: 30
<> Ignored tests: 5
<> Failed tests: 25
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)

14:41:26.727 [pool-21-thread-1] ERROR x.java.compiler.DynamicClassCompiler - [Compilation errors]
LEVENSHTEIN.java:28: error: missing return statement
    }
    ^
14:41:26.729 [pool-21-thread-1] ERROR f.i.l.r.n.s.ConstraintModelBuilder - Unable to compile the change: 
public class LEVENSHTEIN {
    public static int levenshtein(java.lang.String source, java.lang.String target) {
        if ((source.isEmpty()) || (target.isEmpty())) {
            boolean spoonDefaultValue = false;
            try {
                spoonDefaultValue = true;
            } catch (java.lang.Exception __NopolProcessorException) {
            }
            boolean runtimeAngelicValue = fr.inria.lille.repair.nopol.synth.AngelicExecution.angelicValue(spoonDefaultValue);
            if (fr.inria.lille.commons.trace.RuntimeValues.instance(4).isEnabled()) {
                fr.inria.lille.commons.trace.RuntimeValues.instance(4).collectionStarts();
                try{fr.inria.lille.commons.trace.RuntimeValues.instance(4).collectInput("source",source);} catch (Exception ex1) {ex1.printStackTrace();};
                try{fr.inria.lille.commons.trace.RuntimeValues.instance(4).collectInput("target",target);} catch (Exception ex1) {ex1.printStackTrace();};
                fr.inria.lille.commons.trace.RuntimeValues.instance(4).collectOutput(runtimeAngelicValue);
                fr.inria.lille.commons.trace.RuntimeValues.instance(4).collectionEnds();
            }
            if (runtimeAngelicValue)
                return source.isEmpty() ? target.length() : source.length();

        }else
            if ((source.charAt(0)) == (target.charAt(0))) {
                return 1 + (java_programs.LEVENSHTEIN.levenshtein(source.substring(1), target.substring(1)));
            }else {
                return 1 + (java.lang.Math.min(java.lang.Math.min(java_programs.LEVENSHTEIN.levenshtein(source, target.substring(1)), java_programs.LEVENSHTEIN.levenshtein(source.substring(1), target.substring(1))), java_programs.LEVENSHTEIN.levenshtein(source.substring(1), target)));
            }

    }
}
14:41:26.729 [pool-2-thread-1] ERROR fr.inria.lille.repair.nopol.NoPol - Error ExecutionException java.util.concurrent.ExecutionException: xxl.java.compiler.DynamicCompilationException: Aborting: dynamic compilation failed
14:41:26.729 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #8
14:41:26.729 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LEVENSHTEIN:14 which is executed by 6 tests
-1975184878
14:41:26.771 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalReplacer
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
java.lang.AssertionError: expected:<3> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
java.lang.AssertionError: expected:<8> but was:<13>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
14:41:28.071 [pool-24-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (1297 ms)
<> Total tests run: 30
<> Ignored tests: 5
<> Failed tests: 25
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<7>]
java.lang.AssertionError: expected:<3> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<13>]
java.lang.AssertionError: expected:<8> but was:<13>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)

java.lang.StringIndexOutOfBoundsException: String index out of range: 0
    at java.lang.String.charAt(String.java:658)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:20)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
14:41:28.175 [pool-25-thread-1] INFO  f.i.l.c.t.SpecificationTestCasesListener - Tests run finished (1 ms)
<> Total tests run: 1
<> Ignored tests: 0
<> Failed tests: 1
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[String index out of range: 0]
java.lang.StringIndexOutOfBoundsException: String index out of range: 0    at java.lang.String.charAt(String.java:658)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:20)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)

java.lang.StringIndexOutOfBoundsException: String index out of range: 0
    at java.lang.String.charAt(String.java:658)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:20)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
14:41:28.177 [pool-26-thread-1] INFO  f.i.l.c.t.SpecificationTestCasesListener - Tests run finished (1 ms)
<> Total tests run: 1
<> Ignored tests: 0
<> Failed tests: 1
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[String index out of range: 0]
java.lang.StringIndexOutOfBoundsException: String index out of range: 0    at java.lang.String.charAt(String.java:658)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:20)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)

java.lang.StringIndexOutOfBoundsException: String index out of range: 0
    at java.lang.String.charAt(String.java:658)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:20)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:21)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
14:41:28.179 [pool-27-thread-1] INFO  f.i.l.c.t.SpecificationTestCasesListener - Tests run finished (1 ms)
<> Total tests run: 1
<> Ignored tests: 0
<> Failed tests: 1
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[String index out of range: 0]
java.lang.StringIndexOutOfBoundsException: String index out of range: 0    at java.lang.String.charAt(String.java:658)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:20)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:21)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)

java.lang.StringIndexOutOfBoundsException: String index out of range: 0
    at java.lang.String.charAt(String.java:658)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:20)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:21)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:21)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:21)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:21)
14:41:28.180 [pool-28-thread-1] INFO  f.i.l.c.t.SpecificationTestCasesListener - Tests run finished (0 ms)
<> Total tests run: 1
<> Ignored tests: 0
<> Failed tests: 1
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[String index out of range: 0]
java.lang.StringIndexOutOfBoundsException: String index out of range: 0    at java.lang.String.charAt(String.java:658)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:20)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:21)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:21)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:21)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:21)

java.lang.StringIndexOutOfBoundsException: String index out of range: 0
    at java.lang.String.charAt(String.java:658)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:20)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:21)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
14:41:28.185 [pool-29-thread-1] INFO  f.i.l.c.t.SpecificationTestCasesListener - Tests run finished (4 ms)
<> Total tests run: 1
<> Ignored tests: 0
<> Failed tests: 1
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[String index out of range: 0]
java.lang.StringIndexOutOfBoundsException: String index out of range: 0    at java.lang.String.charAt(String.java:658)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:20)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:21)
    at java_programs.LEVENSHTEIN.levenshtein(LEVENSHTEIN.java:23)

java.lang.AssertionError: expected:<3> but was:<8>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)
14:41:28.187 [pool-30-thread-1] INFO  f.i.l.c.t.SpecificationTestCasesListener - Tests run finished (1 ms)
<> Total tests run: 1
<> Ignored tests: 0
<> Failed tests: 1
~ test_0(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<8>]
java.lang.AssertionError: expected:<3> but was:<8>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_0(LEVENSHTEIN_Test.java:8)

java.lang.AssertionError: expected:<3> but was:<6>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)
14:41:28.188 [pool-31-thread-1] INFO  f.i.l.c.t.SpecificationTestCasesListener - Tests run finished (0 ms)
<> Total tests run: 1
<> Ignored tests: 0
<> Failed tests: 1
~ test_1(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<3> but was:<6>]
java.lang.AssertionError: expected:<3> but was:<6>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_1(LEVENSHTEIN_Test.java:14)

java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)
14:41:28.189 [pool-32-thread-1] INFO  f.i.l.c.t.SpecificationTestCasesListener - Tests run finished (0 ms)
<> Total tests run: 1
<> Ignored tests: 0
<> Failed tests: 1
~ test_6(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<4> but was:<5>]
java.lang.AssertionError: expected:<4> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_6(LEVENSHTEIN_Test.java:45)

java.lang.AssertionError: expected:<2> but was:<7>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)
14:41:28.191 [pool-33-thread-1] INFO  f.i.l.c.t.SpecificationTestCasesListener - Tests run finished (1 ms)
<> Total tests run: 1
<> Ignored tests: 0
<> Failed tests: 1
~ test_4(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<2> but was:<7>]
java.lang.AssertionError: expected:<2> but was:<7>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_4(LEVENSHTEIN_Test.java:33)

java.lang.AssertionError: expected:<8> but was:<11>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)
14:41:28.192 [pool-34-thread-1] INFO  f.i.l.c.t.SpecificationTestCasesListener - Tests run finished (1 ms)
<> Total tests run: 1
<> Ignored tests: 0
<> Failed tests: 1
~ test_2(java_testcases.junit.LEVENSHTEIN_Test)
[expected:<8> but was:<11>]
java.lang.AssertionError: expected:<8> but was:<11>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LEVENSHTEIN_Test.test_2(LEVENSHTEIN_Test.java:20)

14:41:28.193 [pool-23-thread-1] DEBUG tests.output - Failing tests with false: 
[test_0(java_testcases.junit.LEVENSHTEIN_Test): String index out of range: 0, test_1(java_testcases.junit.LEVENSHTEIN_Test): String index out of range: 0, test_6(java_testcases.junit.LEVENSHTEIN_Test): String index out of range: 0, test_4(java_testcases.junit.LEVENSHTEIN_Test): String index out of range: 0, test_2(java_testcases.junit.LEVENSHTEIN_Test): String index out of range: 0]
14:41:28.193 [pool-23-thread-1] DEBUG tests.output - Failing tests with true: 
[test_0(java_testcases.junit.LEVENSHTEIN_Test): expected:<3> but was:<8>, test_1(java_testcases.junit.LEVENSHTEIN_Test): expected:<3> but was:<6>, test_6(java_testcases.junit.LEVENSHTEIN_Test): expected:<4> but was:<5>, test_4(java_testcases.junit.LEVENSHTEIN_Test): expected:<2> but was:<7>, test_2(java_testcases.junit.LEVENSHTEIN_Test): expected:<8> but was:<11>]
14:41:28.193 [pool-23-thread-1] INFO  f.i.l.r.n.synth.SMTNopolSynthesizer - Not enough specifications: 0. A trivial patch is "true" or "false", please write new tests specifying SourceLocation java_programs.LEVENSHTEIN:14.
14:41:28.193 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - ----INFORMATION----
14:41:28.198 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb classes : 3
14:41:28.198 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb methods : 9
14:41:28.198 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb Statements Analyzed : 6
14:41:28.198 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb Statements with Angelic Value Found : 0
14:41:28.198 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb inputs in SMT : 0
14:41:28.200 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb SMT level: 0
14:41:28.200 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb variables in SMT : 0
14:41:28.200 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - NoPol Execution time : 17563ms
14:41:28.200 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - 
NO_ANGELIC_VALUE
Command exited with non-zero status 255
25.61user 1.50system 0:18.75elapsed 144%CPU (0avgtext+0avgdata 1897000maxresident)k
46200inputs+5616outputs (3major+533186minor)pagefaults 0swaps


Node: graphene-13.nancy.grid5000.fr



Date: Sun Dec  2 14:41:28 EST 2018

