cd /tmp/DynaMoth_QuixBugs_LIS_;
export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8 -Duser.language=en-US -Duser.country=US -Duser.language=en";
TZ="America/New_York"; export TZ;
export PATH="/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/:$PATH";
export JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/";
time java -Xmx4g -Xms1g -cp /home/tdurieux/defects4j4repair/script/../repair_tools/nopol.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin//../lib/tools.jar fr.inria.lille.repair.Main \
	--mode repair \
	--type pre_then_cond \
	--oracle angelic \
	--synthesis dynamoth \
	--flocal gzoltar \
	--json \
	--solver z3 \
	--solver-path /home/tdurieux/defects4j4repair/script/../libs/z3/build/z3 \
	--complianceLevel 8 \
	--source src/main/java \
	--classpath "target/classes:target/test-classes:/home/tdurieux/.m2/repository/junit/junit/4.11/junit-4.11.jar:/home/tdurieux/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/tdurieux/defects4j4repair/script/../repair_tools/nopol.jar";
	echo "\n\nNode: `hostname`\n";
	echo "\n\nDate: `date`\n";
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Duser.language=en-US -Duser.country=US -Duser.language=en
12:03:34.238 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Source files: [src/main/java]
12:03:34.241 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Classpath: [file:/tmp/DynaMoth_QuixBugs_LIS_/target/classes/, file:/tmp/DynaMoth_QuixBugs_LIS_/target/test-classes/, file:/home/tdurieux/.m2/repository/junit/junit/4.11/junit-4.11.jar, file:/home/tdurieux/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar, file:/home/tdurieux/defects4j4repair/script/../repair_tools/nopol.jar]
12:03:34.241 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Statement type: PRE_THEN_COND
12:03:34.241 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Args: [java_testcases.junit.LIS_Test]
12:03:34.243 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Config: Config{synthesisDepth=3, collectStaticMethods=true, collectStaticFields=false, collectLiterals=false, onlyOneSynthesisResult=true, sortExpressions=true, maxLineInvocationPerTest=250, timeoutMethodInvocation=2000, dataCollectionTimeoutInSecondForSynthesis=900, addWeight=0.19478, subWeight=0.04554, mulWeight=0.0102, divWeight=0.00613, andWeight=0.10597, orWeight=0.05708, eqWeight=0.22798, nEqWeight=0.0, lessEqWeight=0.0255, lessWeight=0.0947, methodCallWeight=0.1, fieldAccessWeight=0.08099, constantWeight=0.14232, variableWeight=0.05195, mode=REPAIR, type=PRE_THEN_COND, synthesis=DYNAMOTH, oracle=ANGELIC, solver=Z3, solverPath='/home/tdurieux/defects4j4repair/script/../libs/z3/build/z3', projectSources=[src/main/java], projectClasspath='[Ljava.net.URL;@2ff4f00f', projectTests=[java_testcases.junit.LIS_Test], complianceLevel=8, outputFolder=., json=true}
12:03:34.243 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Available processors (cores): 32
12:03:34.253 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Free memory: 940 MB
12:03:34.253 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Maximum memory: 3 GB
12:03:34.253 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Total memory available to JVM: 981 MB
12:03:34.253 [main] INFO  fr.inria.lille.repair.nopol.NoPol - Java version: 1.8.0_181
12:03:34.254 [main] INFO  fr.inria.lille.repair.nopol.NoPol - JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/
12:03:34.254 [main] INFO  fr.inria.lille.repair.nopol.NoPol - PATH: /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/:/usr/lib/oar/oardodo:/usr/lib/oar/oardodo:/usr/local/bin:/usr/bin:/bin:/usr/games
12:03:36.511 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #1
12:03:36.511 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LIS:36 which is executed by 4 tests
75383
12:03:36.702 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #2
12:03:36.702 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LIS:34 which is executed by 4 tests
75383
12:03:36.746 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalAdder
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
12:03:36.781 [pool-4-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (14 ms)
<> Total tests run: 16
<> Ignored tests: 0
<> Failed tests: 16
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)

12:03:37.188 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #3
12:03:37.189 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LIS:31 which is executed by 4 tests
75383
12:03:37.234 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalAdder
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
12:03:37.246 [pool-14-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (9 ms)
<> Total tests run: 16
<> Ignored tests: 0
<> Failed tests: 16
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)

12:03:37.372 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #4
12:03:37.372 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LIS:30 which is executed by 4 tests
75383
12:03:37.431 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalAdder
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
12:03:37.441 [pool-24-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (7 ms)
<> Total tests run: 16
<> Ignored tests: 0
<> Failed tests: 16
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)

12:03:37.519 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #5
12:03:37.519 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LIS:29 which is executed by 4 tests
75383
12:03:37.564 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalAdder
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
12:03:37.572 [pool-34-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (6 ms)
<> Total tests run: 16
<> Ignored tests: 0
<> Failed tests: 16
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)

12:03:37.652 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalReplacer
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
12:03:37.659 [pool-44-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (6 ms)
<> Total tests run: 16
<> Ignored tests: 0
<> Failed tests: 16
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)

12:03:37.734 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #6
12:03:37.734 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LIS:27 which is executed by 4 tests
75383
12:03:37.777 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #7
12:03:37.777 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LIS:23 which is executed by 4 tests
75383
12:03:37.817 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalAdder
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
12:03:37.828 [pool-54-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (9 ms)
<> Total tests run: 16
<> Ignored tests: 0
<> Failed tests: 16
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)

12:03:37.910 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #8
12:03:37.911 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LIS:22 which is executed by 4 tests
75383
12:03:37.957 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalAdder
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
12:03:37.966 [pool-64-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (7 ms)
<> Total tests run: 16
<> Ignored tests: 0
<> Failed tests: 16
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)

12:03:38.033 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalReplacer
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
12:03:38.041 [pool-74-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (6 ms)
<> Total tests run: 16
<> Ignored tests: 0
<> Failed tests: 16
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)

12:03:38.122 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #9
12:03:38.122 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LIS:21 which is executed by 4 tests
75383
12:03:38.155 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalAdder
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
12:03:38.163 [pool-84-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (5 ms)
<> Total tests run: 16
<> Ignored tests: 0
<> Failed tests: 16
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)

12:03:38.239 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #10
12:03:38.239 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LIS:20 which is executed by 4 tests
75383
12:03:38.272 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #11
12:03:38.273 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LIS:18 which is executed by 4 tests
75383
12:03:38.308 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - looking with class fr.inria.lille.repair.nopol.spoon.smt.ConditionalAdder
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
java.lang.AssertionError: expected:<3> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
java.lang.AssertionError: expected:<6> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
java.lang.AssertionError: expected:<3> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
12:03:38.315 [pool-94-thread-1] INFO  xxl.java.junit.TestCasesListener - Tests run finished (5 ms)
<> Total tests run: 16
<> Ignored tests: 0
<> Failed tests: 16
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)
~ test_0(java_testcases.junit.LIS_Test)
[expected:<3> but was:<2>]
java.lang.AssertionError: expected:<3> but was:<2>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_0(LIS_Test.java:8)
~ test_1(java_testcases.junit.LIS_Test)
[expected:<6> but was:<5>]
java.lang.AssertionError: expected:<6> but was:<5>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_1(LIS_Test.java:14)
~ test_2(java_testcases.junit.LIS_Test)
[expected:<3> but was:<1>]
java.lang.AssertionError: expected:<3> but was:<1>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_2(LIS_Test.java:20)
~ test_3(java_testcases.junit.LIS_Test)
[expected:<4> but was:<3>]
java.lang.AssertionError: expected:<4> but was:<3>    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at java_testcases.junit.LIS_Test.test_3(LIS_Test.java:26)

12:03:38.392 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #12
12:03:38.392 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LIS:17 which is executed by 4 tests
75383
12:03:38.425 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #13
12:03:38.425 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LIS:15 which is executed by 4 tests
75383
12:03:38.457 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - statement #14
12:03:38.457 [pool-2-thread-1] DEBUG fr.inria.lille.repair.nopol.NoPol - Analysing SourceLocation java_programs.LIS:14 which is executed by 4 tests
75383
12:03:38.489 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - ----INFORMATION----
12:03:38.499 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb classes : 3
12:03:38.499 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb methods : 9
12:03:38.499 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb Statements Analyzed : 10
12:03:38.499 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - Nb Statements with Angelic Value Found : 0
12:03:38.499 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - NoPol Execution time : 4253ms
12:03:38.499 [pool-2-thread-1] INFO  fr.inria.lille.repair.nopol.NoPol - 
NO_ANGELIC_VALUE
Command exited with non-zero status 255
11.67user 0.95system 0:05.14elapsed 245%CPU (0avgtext+0avgdata 478256maxresident)k
45504inputs+5520outputs (3major+154891minor)pagefaults 0swaps


Node: grisou-49.nancy.grid5000.fr



Date: Sun Dec  2 12:03:38 EST 2018

